In [1]:
import numpy as np
from random import normalvariate

In [2]:
data = np.array([[6,148,72,35,0,33.6,0.627,50],[1,85,66,29,0,26.6,0.351,31],[8,183,64,0,0,23.3,0.672,32],[1,89,66,23,94,28.1,0.167,21],[0,137,40,35,168,43.1,2.288,33]])

In [3]:
label=np.array([1,0,1,0,1])

In [4]:
m,n = data.shape
print(m,n)

5 8


In [5]:
def sigmoid(inx):
    return 1.0 / (1 + np.exp(-inx))

In [6]:
def fit(data,alpha=0.01,k=3,iter_num=20):
    '''alpha为学习率，k为v的隐特征数，iter_num为迭代次数
    初始化所需要的参数'''
    m,n = data.shape    #m为样本个数，n为特征个数
    w = np.zeros(n)
    w_0 = 0.
    v = normalvariate(0, 0.2) * np.ones((n, k))
     
    for it in range(iter_num):
        for x in range(m):
            '''前向传播得到预测值'''
            inter_1 = data[x].dot(v)
            inter_2 = np.multiply(data[x],data[x]).dot((np.multiply(v,v)))
            interaction =np.sum(inter_1*inter_1-inter_2)/2
            p = w_0+ w.dot(data[x])+interaction
            print('预测值：',p)
           
            '''损失函数'''
            loss = sigmoid(label[x]*p)-1
            
            '''随机梯度下降，得到各个权重'''
            w_0 = w_0 - alpha*loss*label[0]   
            for i in range(n):
                if data[x, i] != 0:
                    w[i] = w[i] - alpha*loss*label[0]*data[0][i]     
                    for j in range(k):
                        v[i,j]=v[i,j]-alpha*loss*label[0]*(data[0][i]*(inter_1[j])-v[i,j]*data[0][i]*data[0][i])
    return w_0,w,v

In [7]:
w_0,w,v=fit(data)

预测值： 18786.18202115062
预测值： 9264.745137664864
预测值： 38899639.717939235
预测值： 24736872.482154604
预测值： 73153103496.97766
预测值： 111616921707.34055
预测值： 57515144876.10086
预测值： 261430926375139.62
预测值： 161072763807693.5
预测值： 3.7418006597929594e+17
预测值： 5.864973980223777e+17
预测值： 3.145613382763665e+17
预测值： 1.8060217531873865e+21
预测值： 1.0755232997882851e+21
预测值： 1.0510304071684795e+24
预测值： 1.875336671458012e+24
预测值： 1.2286134359810432e+24
预测值： 1.1629268638253915e+28
预测值： 6.735203408316856e+27
预测值： -1.84752490444234e+31
预测值： -2.7819458273453374e+35
预测值： 9.067683748504711e+38
预测值： 2.055345270240118e+43
预测值： 1.209681424330067e+43
预测值： -9.951910102422741e+46
预测值： -1.8151017996539588e+51
预测值： -8.173478424900084e+54
预测值： -1.0285362905227667e+58
预测值： 2.9257963453467544e+63
预测值： 1.5644741825927637e+67
预测值： 2.2121637175212476e+67
预测值： 1.0595718869357182e+67
预测值： 7.90916954981935e+69
预测值： 1.0277352803088698e+70
预测值： 8.732715877296473e+73
预测值： 1.206114751106069e+74
预测值： 5.590613764683022e+73
预测值： -2.3737293

In [8]:
print('w_0:{}\n w:{}\n v:{}'.format(w_0,w,v))

w_0:0.5000000000000003
 w:[ 2.4    74.     36.     13.3     0.     16.8     0.3135 25.    ]
 v:[[ 2.77615869e+129  2.77615869e+129  2.77615869e+129]
 [ 8.56045210e+132  8.56045210e+132  8.56045210e+132]
 [-1.27232864e+133 -1.27232864e+133 -1.27232864e+133]
 [-4.96985403e+132 -4.96985403e+132 -4.96985403e+132]
 [-3.78971982e-001 -3.78971982e-001 -3.78971982e-001]
 [-4.76274872e+132 -4.76274872e+132 -4.76274872e+132]
 [-8.54796488e+130 -8.54796488e+130 -8.54796488e+130]
 [-7.48963307e+132 -7.48963307e+132 -7.48963307e+132]]


# 单步调试

In [ ]:
alpha = 0.01
k=3
w = np.zeros(n)
w_0 = 0.
v = normalvariate(0, 0.2) * np.ones((n, k))
print(v)

In [ ]:
interaction

In [ ]:
data[0].dot(w)

In [ ]:
data[0].dot(v)

In [ ]:
label[0]

In [ ]:
def sigmoid(inx):
    return 1.0 / (1 + np.exp(-inx))

In [ ]:
inter_1 = data[0].dot(v)
inter_2 = np.multiply(data[0],data[0]).dot((np.multiply(v,v)))
interaction =np.sum(inter_1*inter_1-inter_2)/2
p = w_0+ w.dot(data[0])+interaction

In [ ]:
inter_1

In [ ]:
loss = sigmoid(label[0]-p)-1
loss

In [ ]:
w_0 = w_0 - alpha*loss*label[0]   
w_0

In [ ]:
w

In [ ]:
for i in range(n):
    w[i] = w[i] - alpha*loss*label[0]*data[0][i]
    for j in range(k):
        v[i,j]=v[i,j]-alpha*loss*label[0]*(data[0][i]*(inter_1[j])-v[i,j]*data[0][i]*data[0][i])
print(v)
    

In [ ]:
sum(inter_1*inter_1-inter_2)/2

In [ ]:
for it in range(5):
    for x in range(m):
        inter_1 = data[x].dot(v)
        inter_2 = np.multiply(data[x],data[x]).dot((np.multiply(v,v)))
        interaction =np.sum(inter_1*inter_1-inter_2)/2
        p = w_0+ w.dot(data[x])+interaction
        loss = sigmoid(label[0]*p)-1
        w_0 = w_0 - alpha*loss*label[0]   
        for i in range(n):
            w[i] = w[i] - alpha*loss*label[0]*data[0][i]     
            for j in range(k):
                v[i,j]=v[i,j]-alpha*loss*label[0]*(data[0][i]*(inter_1[j])-v[i,j]*data[0][i]*data[0][i])
    print(w,v)
    
     